config/routes.rb
EntityManager::Application.routes.draw do

  
  root :to => redirect('/entities')
  
  
  resources :entities do
  	resources :local_identities
  end   
  
  resources :local_identities
  
 
  match 'get_by_alias'  => 'entities#get_by_alias'
  match 'getIdentity'  => 'entities#getIdentity'
  match 'addRelation'  => 'relationships#create'
  match 'removeRelation'  => 'relationships#destroy'
  match 'getMasters'  => 'relationships#getMasters'
  match 'relationships/getMasters'  => 'relationships#getMasters'
  match 'getSlaves'  => 'relationships#getSlaves'
  match 'relationships/getSlaves'  => 'relationships#getSlaves'    
  match 'addAliasToIdentity'  => 'local_identities#addAliasToIdentity'
  match 'getAllMasters'  => 'relationships#getAllMasters'
  match 'getAllSlaves'  => 'relationships#getAllSlaves'
  
  match 'auth/:provider/callback' => 'sessions#create' #, :as => :login
  match 'logout' => 'sessions#destroy' #, :as => :logout   

end

app/models/entity.rb
class Entity < ActiveRecord::Base
  has_many :local_identities, :dependent => :destroy
  has_many :owners, :through => :local_identities  
  has_many :slavery, :class_name => "Relationship", :foreign_key => "master_id"
  has_many :slaves, :through => :slavery, :source => :slave
  has_many :mastery, :class_name => "Relationship", :foreign_key => "slave_id"
  has_many :masters, :through => :mastery, :source => :master
  validates :uuid, :uniqueness => true
  
  default_scope order('updated_at DESC')
  paginates_per 15
  
  #if range is -1 -> get all masters
  #if range > 0 -> it defines how far in the graph we will search
  #if range == 0 -> stop finding the predecessors
  def getAllMasters(range)
    result = []
    parents = self.masters
    if parents.length == 0 || range == 0
      return result
    elsif range > 0
      result = result | parents
      range = range - 1
      masters.each do |entity|
        result = result | entity.getAllMasters(range)
      end
    else
      result = result | parents
      masters.each do |entity|
        result = result | entity.getAllMasters(-1) 
      end
    end
    result
  end
  
  #if range is -1 -> get all slaves
  #if range > 0 -> it defines how far in the graph we will search
  #if range == 0 -> stop finding the children
  def getAllSlaves(range)
    result = []
    children = self.slaves
    if children.length == 0 || range == 0
      return result
    elsif range > 0
      result = result | children
      range = range - 1
      children.each do |entity|
        result = result | entity.getAllSlaves(range)
      end
    else
      result = result | children
      children.each do |entity|
        result = result | entity.getAllSlaves(-1) 
      end
    end
    result
  end
end
 

app/controllers/entities_controller.rb
# This file is app/controllers/entities_controller.rb

class EntitiesController < ApplicationController
	respond_to :html, :xml, :json
		 
  def index
  	@current_user ||= Owner.find_by_id(session[:user_id])    
    respond_to do |format|
      format.html {
        @entities = Entity.order("updated_at DESC").page(params[:page]).per(15)
      }
      format.xml {
        @entities = Entity.order("updated_at DESC")
      }
    end
    respond_with(@entities)
  end
  
  def get_by_alias    
    respond_to do |format|
      format.html {
        @owner = Owner.find_by_id(params[:owner])
        p @owner.inspect
        @entity = LocalIdentity.find_by_alias(params[:search_terms], @owner.id)
        p @entity.inspect
        unless @entity.nil? or @owner.nil?
          redirect_to entity_path(@entity) and return
        end
        if @owner.nil?
          flash[:notice] = "Unknown owner"
        else   
          flash[:notice] = "Entity with local alias '#{params[:search_terms]}' and owner '#{params[:owner]}' does not exist!"
        end
        redirect_to entities_path
      }
      format.xml {
        unless (@user = Owner.find_by_id(params[:owner]))
          raise EntityManager::OwnerNotFound
        end 
        @entity = LocalIdentity.find_by_alias(params[:search_terms], @user.id)
        if @entity.nil?
          raise EntityManager::EntityNotFound
        else
          respond_with @entity
        end
      }
    end     
    
  end

  def show
    id = params[:id] # retrieve internal entity ID from URI route
    @entity = Entity.find_by_id(id) # look up entity by unique internal ID

    if @entity == nil
      flash[:notice] = "Entity with internal ID '#{id}' does not exist!"
      redirect_to entities_path
    else
      @slaves = @entity.slaves  
      @masters = @entity.masters     
      @entity
    end
    @localIDs = @entity.local_identities
    # will render app/views/entities/show.html.haml by default
  end
  
  def getIdentity
    uuid = params[:uuid] 
    @entity = Entity.find_by_uuid(uuid) 

    if @entity == nil
      respond_to do |format|
        format.html {
          flash[:notice] = "Entity with uuid '#{params[:uuid]}' does not exist!"        
          redirect_to entities_path
        }
        format.xml {
          raise EntityManager::EntityNotFound
        }
      end 
    else
      respond_with @entity
    end                 
  end
  
  def new
    # default: render 'new' template
  end

  def create                  
    #raise params.inspect    
    new_params = {} # params for LocalID
    respond_to do |format|
      format.html { 
        @owner = Owner.find_by_id(session[:user_id]) 
        new_params.store("localid", params[:local_identities][:localid])
        new_params.store("description", params[:local_identities][:description])
        
      }
      format.xml {
        @owner = Owner.find(params[:owner])
        new_params.store("localid", params[:localid])
        new_params.store("description", params[:description])
      }
    end    
    
    @localIdentity = LocalIdentity.create!(new_params)
    @localIdentity.owner = @owner
    new_params2 = {} #params for entity
    new_params2.store("uuid", SecureRandom.uuid)
    new_params2.store("schema", 'urn:entityID:')
    
    respond_to do |format|
      format.html { 
        #for now just copy the description of local identity
        new_params2.store("description", params[:local_identities][:description])        
      }
      format.xml {
        new_params2.store("description", params[:description])        
      }
    end        
    #raise new_params2.inspect
    @entity = Entity.create!(new_params2)
    @entity.local_identities << @localIdentity

    respond_to do |format|
      format.html { 
        flash[:notice] = "'#{@entity.description}' was successfully registered."
        redirect_to entities_path  
        return      
      }
      format.xml {
        respond_with @entity        
      }
    end           
  end
  
  
  def edit
    @entity = Entity.find_by_id(params[:id])
    if @entity == nil
      flash[:notice] = "Entity with internal ID '#{params[:id]}' does not exist!"
      redirect_to entities_path
    else
      @entity
    end
  end

  def update
    @entity = Entity.find_by_id(params[:id])
    if @entity == nil
      flash[:notice] = "Entity with internal ID '#{params[:id]}' does not exist!"
      redirect_to entities_path
    else
      @entity
    end
    @entity.update_attributes!(params[:entity])
    respond_to do |client_wants|
      client_wants.html {  
        flash[:notice] = "#{@entity.uuid} was successfully updated."
        redirect_to entity_path(@entity)
        return
      } # as before
      client_wants.xml  {  render :xml => @entity.to_xml    }
    end
      
  end

  def destroy
    @entity = Entity.find_by_id(params[:id])
    if @entity == nil
      flash[:notice] = "Entity with internal ID '#{params[:id]}' does not exist!"
      redirect_to entities_path    
    end
    @entity.destroy
    flash[:notice] = "Entity '#{@entity.uuid}' deleted."
    redirect_to entities_path
  end

  def login
  end
  
end

app/views/entities/_local_identity.html.haml
-# sigle row about one local ID of the entity
%tr
	%td= local_identity.localid
	%td= local_identity.description
	%td= local_identity.owner_id
	%td= button_to 'Delete', entity_local_identity_path(@entity,local_identity), :method => :delete, :confirm => 'Are you sure?'

app/views/entities/edit.html.haml
%h2 Update Entity

= form_tag entity_path(@entity), :method => :put do
  = label :entity, :uuid, 'UUID'
  = text_field :entity, :uuid, :disabled => 'on'

  = label :entity, :description, 'Description'
  = text_field :entity, :description

  = submit_tag 'Save Changes'

app/views/entities/index.html.haml
-#  This file is app/views/entities/index.html.haml
= link_to 'Register new entity', new_entity_path

%h2 Get Entity by local alias

= form_tag :action => 'get_by_alias' do
  %table
    %tbody      
      %tr
        %td 
          %label{:for => 'search_terms'} Search Terms
        %td= text_field_tag 'search_terms'
        %td
          %label{:for => 'owner'} Owner ID 
        %td
          - if @current_user.nil? then ownerID=nil else ownerID=@current_user.id end
          = text_field_tag 'owner', value = ownerID, :size => 3
        %td= submit_tag 'Search by Alias'

%h2 Get Entity by UUID

= form_tag :action => 'getIdentity' do
  %table
    %tbody      
      %tr
        %td
          %label{:for => 'uuid'} UUID for lookup
        %td= text_field_tag 'uuid', value = nil, :size => 27
        %td= submit_tag 'Search by UUID'

%h2 All Entities

%table#entities
  %thead
    %tr
      %th Entity UUID
      %th Description
      %th Details & Edit
      -#      %th Edit
      %th Slaves
      %th Masters
      %th Delete                  
  %tbody
    - @entities.each do |entity|
      %tr
        %td= entity.uuid 
        %td= entity.description
        %td= link_to "More about #{entity.uuid}", entity_path(entity)
        -#        %td= link_to 'Edit', edit_entity_path(entity)
        %td= link_to "List of slaves", getSlaves_path(:uuid => entity.uuid)
        %td= link_to "List of masters", getMasters_path(:uuid => entity.uuid)
        %td= button_to 'Delete', entity_path(entity), :method => :delete, :confirm => 'Are you sure?'
        
= paginate @entities

app/views/entities/new.html.haml
%h2 Register New Entity

= form_tag entities_path, :method => :post do

  = label :local_identities, :localid, "Local ID"
  = text_field :local_identities, :localid

  = label :local_identities, :description, 'Description'
  = text_field :local_identities, :description

  = submit_tag 'Save Changes'

app/views/entities/show.html.haml
-# in app/views/entities/show.html.haml
= link_to 'Back to entity list', entities_path

%h2 Details about #{@entity.uuid}

%ul#details
  %li
    UUID:
    = @entity.uuid
  %li
    Inserted on:
    = @entity.created_at.strftime("%d. %B %Y, %H:%M:%S,%L %Z")

%h3 Description:

%p#description= @entity.description

= link_to 'Edit entity description', edit_entity_path(@entity)

-# This Delete link will not really be a link, but a form:
= button_to 'Delete', entity_path(@entity), :method => :delete, :confirm => 'Are you sure?'

%h3 List of local identities - aliases for #{@entity.uuid}

%table#local_identities
  %thead
    %tr
      %th Local ID
      %th Name
      %th Owner
      %th Delete   
  %tbody
    = render :partial=>'local_identity', :collection=>@localIDs

%h3 List of slaves for #{@entity.uuid}

%table#slaves
  %thead
    %tr
      %th Entity UUID
      %th Description               
  %tbody
    - @slaves.each do |entity|
      %tr
        %td= entity.uuid 
        %td= entity.description
        %td= link_to "More about #{entity.uuid}", entity_path(entity)
        
%h3 List of masters for #{@entity.uuid}

%table#masters
  %thead
    %tr
      %th Entity UUID
      %th Description               
  %tbody
    - @masters.each do |entity|
      %tr
        %td= entity.uuid 
        %td= entity.description
        %td= link_to "More about #{entity.uuid}", entity_path(entity)
%p

= link_to 'Add Local ID', new_entity_local_identity_path(@entity)