config/routes.rb
EntityManager::Application.routes.draw do

  
  root :to => redirect('/entities')
  
  
  resources :entities do
  	resources :local_identities
  end   
  
  resources :local_identities
  
 
  match 'get_by_alias'  => 'entities#get_by_alias'
  match 'getIdentity'  => 'entities#getIdentity'
  match 'addRelation'  => 'relationships#create'
  match 'removeRelation'  => 'relationships#destroy'
  match 'getMasters'  => 'relationships#getMasters'
  match 'relationships/getMasters'  => 'relationships#getMasters'
  match 'getSlaves'  => 'relationships#getSlaves'
  match 'relationships/getSlaves'  => 'relationships#getSlaves'    
  match 'addAliasToIdentity'  => 'local_identities#addAliasToIdentity'
  match 'getAllMasters'  => 'relationships#getAllMasters'
  match 'getAllSlaves'  => 'relationships#getAllSlaves'
  
  match 'auth/:provider/callback' => 'sessions#create' #, :as => :login
  match 'logout' => 'sessions#destroy' #, :as => :logout   

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :master, :class_name => "Entity"
  belongs_to :slave, :class_name => "Entity"  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	respond_to :html, :xml, :json
	
	def create	  
    master_uuid = params[:master]
    slave_uuid = params[:slave] 
    @entity_master = Entity.find_by_uuid(master_uuid) 
    @entity_slave = Entity.find_by_uuid(slave_uuid) 
    
    if @entity_master == nil or @entity_slave == nil
      raise EntityManager::EntityNotFound
    else
      @entity_master.slaves << @entity_slave unless @entity_master.slaves.where(uuid: @entity_slave.uuid).any?
      @slaves = @entity_master.slaves
      respond_with(@slaves) do |format|  
        format.xml { render :xml => @slaves }  
      end  
    end 
	end
	
	def destroy	  
    master_uuid = params[:master]
    slave_uuid = params[:slave] 
    @entity_master = Entity.find_by_uuid(master_uuid) 
    @entity_slave = Entity.find_by_uuid(slave_uuid) 
    
    if @entity_master == nil or @entity_slave == nil
      raise EntityManager::EntityNotFound
    else
      @entity_master.slaves.delete(@entity_slave) if @entity_master.slaves.where(uuid: @entity_slave.uuid).any?
      @slaves = @entity_master.slaves
      respond_with(@slaves) do |format|  
        format.xml { render :xml => @slaves }  
      end  
    end 
	end
	
	def getMasters
	  uuid = params[:uuid]
    @entity = Entity.find_by_uuid(uuid) 
    
    if @entity == nil 
      raise EntityManager::EntityNotFound
    else
      @masters = @entity.masters 
      respond_with(@masters) do |format|  
        format.xml { render :xml => @masters }  
        format.html {}
      end  
    end 
	end
	
	def getAllMasters
    uuid = params[:uuid]
    range = params[:range].to_i
    @entity = Entity.find_by_uuid(uuid)     
    
    if @entity == nil 
      raise EntityManager::EntityNotFound
    else      
      @result = @entity.getAllMasters(range)
      
      respond_with(@result) do |format|  
        format.xml { render :xml => @result }  
        format.html {}
      end  
    end 
  end
	
	def getSlaves
	  uuid = params[:uuid]
    @entity = Entity.find_by_uuid(uuid) 
    
    if @entity == nil 
      raise EntityManager::EntityNotFound
    else
      @slaves = @entity.slaves 
      respond_with(@slaves) do |format|  
        format.xml { render :xml => @slaves }  
        format.html {}
      end  
    end 
	end
	
	def getAllSlaves
    uuid = params[:uuid]
    range = params[:range].to_i
    @entity = Entity.find_by_uuid(uuid)     
    
    if @entity == nil 
      raise EntityManager::EntityNotFound
    else      
      @result = @entity.getAllSlaves(range)
      
      respond_with(@result) do |format|  
        format.xml { render :xml => @result }  
        format.html {}
      end  
    end 
  end
  
end

app/views/relationships/getMasters.html.haml
-# in app/views/relationships/getSlaves.html.haml
= link_to 'Back to entity list', entities_path

%h2 Masters of #{@entity.uuid}

%ul#details
  %li
    UUID:
    = @entity.uuid
  %li
    Inserted on:
    = @entity.created_at.strftime("%d. %B %Y, %H:%M:%S,%L %Z")

%h3 Description:

%p#description= @entity.description

%h3 List of masters for #{@entity.uuid}

%table#masters
  %thead
    %tr
      %th Entity UUID
      %th Description               
  %tbody
    - @masters.each do |entity|
      %tr
        %td= entity.uuid 
        %td= entity.description
        %td= link_to "More about #{entity.uuid}", entity_path(entity)
        

app/views/relationships/getSlaves.html.haml
-# in app/views/relationships/getSlaves.html.haml
= link_to 'Back to entity list', entities_path

%h2 Slaves of #{@entity.uuid}

%ul#details
  %li
    UUID:
    = @entity.uuid
  %li
    Inserted on:
    = @entity.created_at.strftime("%d. %B %Y, %H:%M:%S,%L %Z")

%h3 Description:

%p#description= @entity.description

%h3 List of slaves for #{@entity.uuid}

%table#slaves
  %thead
    %tr
      %th Entity UUID
      %th Description               
  %tbody
    - @slaves.each do |entity|
      %tr
        %td= entity.uuid 
        %td= entity.description
        %td= link_to "More about #{entity.uuid}", entity_path(entity)
        